routes/web.php
<?php
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', 'HomeController@index')->name('home');
Route::get('/detail-ikan/{id}', 'HomeController@detail')->name('detail-ikan');
Route::get('/keluar', 'HomeController@logout')->name('keluar');

Route::get('/masuk','HomeController@login')->name('masuk');
Route::get('/daftar','HomeController@register')->name('daftar');
Route::post('/daftar-submit','HomeController@registersubmit')->name('register.submit');
Route::post('/login-submit','HomeController@loginsubmit')->name('login.submit');
Route::middleware('pelanggan-only')->group(function(){
    Route::get('/profil', 'HomeController@profil')->name('profil');
    Route::post('/profil-store', 'HomeController@profilstore')->name('profil.store');
    Route::get('/insert/cart/{id}', 'HomeController@insertcart')->name('insertcart');
    Route::get('/delete/cart/{id}', 'HomeController@deletecart')->name('deletecart');
    Route::get('/update/cart/{id}', 'HomeController@updatecart')->name('updatecart');
    Route::get('/cart', 'HomeController@cart')->name('cart');
    Route::get('/checkout', 'HomeController@checkout')->name('checkout');
    Route::post('/pembelian', 'HomeController@pembelian')->name('pembelian');
    Route::get('/list-pembelian', 'HomeController@listpembelian')->name('list.pembelian');
    Route::get('/pembelian/{id}/bayar', 'PembelianController@bayarpembelian')->name('pembayaran');
    Route::get('/pembelian/{id}/batal', 'PembelianController@batal')->name('pembayaran.batal');
    Route::post('/pembayaran/store', 'PembelianController@store')->name('pembayaran.store');
});

Route::prefix('admin')->group(function () {
    Auth::routes();
});

Route::middleware('auth')->group(function(){
    Route::get('/admin/dashboard','DashboardController@index')->name('dashboard');
    Route::middleware('admin-only')->group(function(){
        Route::resource('/admin/nelayan','NelayanController');
        Route::get('nelayandatatable','NelayanController@datatable')->name('nelayan.datatable');
        Route::resource('/admin/nelayan','NelayanController');
        Route::get('nelayandatatable','NelayanController@datatable')->name('nelayan.datatable');
        Route::resource('/admin/kabupaten','KabupatenController');
        Route::get('kabupatendatatable','KabupatenController@datatable')->name('kabupaten.datatable');
        Route::resource('admin/pelanggan', 'PelangganController');
        Route::resource('admin/admin', 'AdminController');
    });

    Route::resource('admin/ikan', 'IkanController');
    Route::get('ikandatatable','IkanController@datatable')->name('ikan.datatable');
    Route::resource('admin/tambak', 'TambakController');
    Route::get('tambakdatatable','TambakController@datatable')->name('tambak.datatable');

    Route::get('transaksi', 'TransaksiController@index');
    Route::get('transaksi/{transaksi_id}/detail', 'TransaksiController@detail')->name('transaksi.detail');
    Route::put('transaksi/{transaksi_id}/change-status', 'TransaksiController@changeStatus')->name('transaksi.change-status');
});

Route::get('ikan', 'ListingController@ikan');
Route::get('tambak', 'ListingController@tambak');
Route::get('tambak/{id}', 'ListingController@detailTambak');

app/Kabupaten.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Kabupaten extends Model
{
    protected $table = 'kabupaten';

    protected $fillable = [
        'id',
        'ongkir',
        'nama',
        
    ];

    public static function defaultValues(){
        return [
            'nama' => '', 
            'ongkir' => '', 
        
        ];
    }
}

app/Http/Controllers/KabupatenController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Kabupaten;
use Yajra\Datatables\Datatables;
use Auth;
use DB;
use App\User;
class KabupatenController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('admin.kabupaten.index');
    }

    public function datatable(){
        
        $data = DB::table('kabupaten')->orderBy('created_at','DESC')->get();
            
        
      
        return Datatables::of($data)->make(true);
    }


    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $input = Kabupaten::defaultValues();
        return view('admin/kabupaten/form', compact('input'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'nama' => 'required|unique:kabupaten',
            'ongkir' => 'required'
        ]);
        $input = $request->all();
        Kabupaten::create($input);
        return redirect()->route('kabupaten.index')->with('success', 'Berhasil menambah data');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $input = Kabupaten::find($id);
        
        return view('admin/kabupaten/form', compact('input'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'nama' => 'required',
            'ongkir' => 'required'
        ]);

        $kabupaten = Kabupaten::find($id);

        $input = $request->all();
        $kabupaten->update($input);

        return redirect()->route('kabupaten.index')->with('success', 'Berhasil mengubah data');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $kabupaten = Kabupaten::find($id);
        
    
        $kabupaten->delete();
        return 1;
    }
}

resources/views/admin/kabupaten/form.blade.php
@extends('admin.template')
@section('title')
Kabupaten
@endsection

@section('breadcumb')
Form Kabupaten
@endsection

@section('content')

<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <div class="card-title">
                        Form Kabupaten
                    </div>
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-12">
                            <form method="post" enctype="multipart/form-data" id="form" action="{{ (!isset($input['id'])) ? route('kabupaten.store') : route('kabupaten.update', ['id' => $input['id']]) }}">
                                {{csrf_field()}}

                                @isset($input['id'])
                                    {{ method_field('PUT')}}
                                @endisset
                               
                               
                               
                                <div class="form-group">
                                    <label for="">Nama Kabupaten</label>
                                    <input type="text" class="form-control col-md-6 input-value" id="Nama" name="nama" required value=" {{ old('nama', $input['nama']) }} ">
                                </div>

                                <div class="form-group">
                                    <label for="">Jumlah Ongkir</label>
                                    <input type="text" class="form-control col-md-6 input-value" id="Ongkir" name="ongkir" required value=" {{ old('ongkir', $input['ongkir']) }} ">
                                </div>
                               

                                <div class="form-group">
                                    <input type="submit" value="Simpan" class="btn btn-primary float-right">
                                </div>
                                        
                            </form>
                             
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/admin/kabupaten/index.blade.php
@extends('admin.template')
@section('title')
Kabupaten
@endsection

@section('breadcumb')
Kabupaten
@endsection

@section('css')
<link rel="stylesheet" href="{{asset('admin/plugins/datatables.net-bs/css/dataTables.bootstrap.min.css')}}">
<link rel="stylesheet" href="{{asset('admin/plugins/fontawesome-free/css/all.min.css')}}">
  <!-- Ionicons -->

  <!-- DataTables -->
  <link rel="stylesheet" href="{{asset('admin/plugins/datatables-bs4/css/dataTables.bootstrap4.css')}}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{{asset('admin/dist/css/adminlte.min.css')}}">
@endsection

@section('content')

<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <div class="card-title">
                        Data Kabupaten
                    </div>
                    <div class="card-tools">
                        <a href=" {{ route('kabupaten.create') }} " class="btn btn-primary btn-tambah">Tambah Data <i class="fa fa-plus"></i></a>
                    </div>
                </div>
                <div class="card-body">
                    <br>
                    <div>
                      <table id="Table" class="table table-bordered table-hover">
                        <thead>
                          <tr>
                            <th>Nama</th>
                            <th>Ongkir</th>
                            <th></th>
                          </tr>
                        </thead>
                        
                       
                      </table>
                    </div>
                </div>  
            </div>
        </div>
    </div>
</div>
@endsection

@section('js')
<script src="{{asset('admin/plugins/datatables.net/js/jquery.dataTables.min.js')}}"></script>
<script src="{{asset('admin/plugins/datatables.net-bs/js/dataTables.bootstrap.min.js')}}"></script>
<script src="{{asset('admin/plugins/datatables/jquery.dataTables.js')}}"></script>
<script src="{{asset('admin/plugins/datatables-bs4/js/dataTables.bootstrap4.js')}}"></script>
<script>

    $(document).ready(function(){
        $('.likabupaten').addClass('active');
      
       @if(session()->has('success'))
            toastr.success("{{session('success')}}")
            
       @endif
       
    })
   
    var Table =  $('#Table').DataTable({
                processing: true,
                serverSide: true,
                responsive: true,
                "paging": true,
                "lengthChange": true,
                "searching": true,
                "ordering": true,
                "info": true,
                "autoWidth": false,
                ajax: '{!! route('kabupaten.datatable') !!}',
                columns:[
                  {'data': 'nama'},
                  {'data': 'ongkir'},
                  {
                    data:"id",
                    
                    render: function(data, type, row){
                      
                        var button = `<a href="{{ route('kabupaten.edit', ['id' => ':id' ]) }}" class="btn btn-warning btn-edit"><i class="fa fa-edit text-white"></i></a>
                                      <a href="#" data-id=":idhapus" class="btn btn-danger btn-delete"><i class="fa fa-trash text-white"></i></a>
                        `
                                button = button.replace(':id',data);
                                button = button.replace(':idhapus',data);
                        return button;
                    }
                  }
                  
                ],
                "order": [[1,'asc']],
    
                rowId: 'id',
               
            });

            $(document).on('click', '.btn-delete', function(){
                var id = this.attributes['data-id'].value;
                var urlsnya = '{{ route("kabupaten.destroy", ":id") }}';
                    urlsnya = urlsnya.replace(':id', id);
                $.confirm({
                    theme: 'material',
                    title: 'Warning!',
                    content: 'Apakah anda yakin ingin menghapus data ?',
                    buttons: {
                        Yes: function () {
                            $.ajax({
                            type: 'POST',
                            dataType: 'json',
                            data: {
                                id: id,
                                "_token": "{{ csrf_token() }}",
                                _method: 'DELETE'
                            },
                            url: urlsnya,
                            })
                            .done(function(response) {
                                if(response == 1) {
                                    toastr.error('Data berhasil dihapus')
                                    Table.ajax.reload();
                                }
                            })
                            .fail(function() {
                                $.alert('Delete process fail');
                            })
                            .always(function() {
                                console.log("complete");
                            });
                        },
                        No: function () {
                        return;
                        }
                    }
                });
            });
   

  
</script>
@endsection