routes/web.php
<?php
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', 'HomeController@index')->name('home');
Route::get('/detail-ikan/{id}', 'HomeController@detail')->name('detail-ikan');
Route::get('/keluar', 'HomeController@logout')->name('keluar');

Route::get('/masuk','HomeController@login')->name('masuk');
Route::get('/daftar','HomeController@register')->name('daftar');
Route::post('/daftar-submit','HomeController@registersubmit')->name('register.submit');
Route::post('/login-submit','HomeController@loginsubmit')->name('login.submit');
Route::middleware('pelanggan-only')->group(function(){
    Route::get('/profil', 'HomeController@profil')->name('profil');
    Route::post('/profil-store', 'HomeController@profilstore')->name('profil.store');
    Route::get('/insert/cart/{id}', 'HomeController@insertcart')->name('insertcart');
    Route::get('/delete/cart/{id}', 'HomeController@deletecart')->name('deletecart');
    Route::get('/update/cart/{id}', 'HomeController@updatecart')->name('updatecart');
    Route::get('/cart', 'HomeController@cart')->name('cart');
    Route::get('/checkout', 'HomeController@checkout')->name('checkout');
    Route::post('/pembelian', 'HomeController@pembelian')->name('pembelian');
    Route::get('/list-pembelian', 'HomeController@listpembelian')->name('list.pembelian');
    Route::get('/pembelian/{id}/bayar', 'PembelianController@bayarpembelian')->name('pembayaran');
    Route::get('/pembelian/{id}/batal', 'PembelianController@batal')->name('pembayaran.batal');
    Route::post('/pembayaran/store', 'PembelianController@store')->name('pembayaran.store');
});

Route::prefix('admin')->group(function () {
    Auth::routes();
});

Route::middleware('auth')->group(function(){
    Route::get('/admin/dashboard','DashboardController@index')->name('dashboard');
    Route::middleware('admin-only')->group(function(){
        Route::resource('/admin/nelayan','NelayanController');
        Route::get('nelayandatatable','NelayanController@datatable')->name('nelayan.datatable');
        Route::resource('/admin/nelayan','NelayanController');
        Route::get('nelayandatatable','NelayanController@datatable')->name('nelayan.datatable');
        Route::resource('/admin/kabupaten','KabupatenController');
        Route::get('kabupatendatatable','KabupatenController@datatable')->name('kabupaten.datatable');
        Route::resource('admin/pelanggan', 'PelangganController');
        Route::resource('admin/admin', 'AdminController');
    });

    Route::resource('admin/ikan', 'IkanController');
    Route::get('ikandatatable','IkanController@datatable')->name('ikan.datatable');
    Route::resource('admin/tambak', 'TambakController');
    Route::get('tambakdatatable','TambakController@datatable')->name('tambak.datatable');

    Route::get('transaksi', 'TransaksiController@index');
    Route::get('transaksi/{transaksi_id}/detail', 'TransaksiController@detail')->name('transaksi.detail');
    Route::put('transaksi/{transaksi_id}/change-status', 'TransaksiController@changeStatus')->name('transaksi.change-status');
});

Route::get('ikan', 'ListingController@ikan');
Route::get('tambak', 'ListingController@tambak');
Route::get('tambak/{id}', 'ListingController@detailTambak');

app/Tambak.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Tambak extends Model
{
    public $table = 'tambak';
    protected $fillable = [
        'nama_tambak', 'alamat', 'no_telp','foto','user_id', 'status'
    ];

    public function user() {
        return $this->belongsTo('App\User');
    }

    public static function defaultValues(){
        return [
            'nama_tambak' => '', 
            'alamat' => '', 
            'no_telp' => '',
            'foto' => '',
            'user_id' => '', 
            'status' => ''
        ];
    }
}

app/Http/Controllers/TambakController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\StoreTambak;
use Illuminate\Http\Request;
use App\Tambak;
use Yajra\Datatables\Datatables;
use Auth;
use DB;
use App\User;

class TambakController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if(Auth::user()->level == 1){
            $tambak = Tambak::all(); 
        }
        else{
            $tambak = Tambak::where('user_id',Auth::user()->id)->get();
            
        }
        
        return view('admin.tambak.index', compact('tambak'));
    }

    public function datatable(){
        if(Auth::user()->level == 1){
            $data = DB::table('tambak')->join('users','tambak.user_id','users.id')
                                     ->select('tambak.*','users.nama as nama_pemilik')
                                     ->orderBy('tambak.created_at','DESC')
                                     ->get(); 
        }
        else{
            $data = DB::table('tambak')->join('users','tambak.user_id','users.id')
                                     ->select('tambak.*','users.nama as nama_pemilik')
                                     ->where('tambak.user_id', Auth::user()->id)
                                     ->orderBy('tambak.created_at','DESC')
                                     ->get();
            
        }
      
        return Datatables::of($data)->make(true);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $input = Tambak::defaultValues();
        if(Auth::user()->level == 1){
            $user = User::where('level' , 0)->get(); 
        }
        else{
            $user = Auth::user();
        }
        
        return view('admin/tambak/form', compact('input', 'user'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreTambak $request)
    {
       
        $input = $request->all();
        $input['foto'] = '';

        if($request->hasFile('foto')){
            $request->foto->store('foto');
            $input['foto'] = $request->foto->hashName();
        }

        Tambak::create($input);

        return redirect()->route('tambak.index')->with('success', 'Berhasil menambah tambak');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $input = Tambak::find($id);
        if(Auth::user()->level == 1){
            $user = User::where('level' , 0)->get(); 
        }
        else{
            $user = Auth::user();
        }
        return view('admin/tambak/form', compact('input', 'user'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(StoreTambak $request, $id)
    {
        $tambak = Tambak::find($id);

        if($request->hasFile('foto')){
            //remove old photos
            if(is_file('storage/foto/'.$tambak->foto)){
                unlink('storage/foto/'.$tambak->foto);
            }
            $request->foto->store('foto');
            $rename = $request->foto->hashName();
        } else {
            $rename = $tambak->foto;
        }

        $input = $request->all();

        $input['foto'] = $rename;

        $tambak->update($input);

        return redirect()->route('tambak.index')->with('success', 'Berhasil mengubah data tambak');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {

        $tambak = Tambak::find($id);
        
        if($tambak->foto != ''){
            //remove old photos
            if(is_file('storage/foto/'.$tambak->foto)){
                unlink('storage/foto/'.$tambak->foto);
            }
        }
        $tambak->delete();
        return 1;
    }
}

resources/views/admin/tambak/form.blade.php
@extends('admin.template')
@section('title')
Tambak
@endsection

@section('breadcumb')
Form Tambak
@endsection

@section('content')

<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <div class="card-title">
                        Form Tambak
                    </div>
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-12">
                            <form method="post" enctype="multipart/form-data" id="form" action="{{ (!isset($input['id'])) ? route('tambak.store') : route('tambak.update', ['id' => $input['id']]) }}">
                                {{csrf_field()}}

                                @isset($input['id'])
                                    {{ method_field('PUT')}}
                                @endisset
                               
                                @if(Auth::user()->level == 1)
                                    <div class="form-group">
                                        <label for="">Pemilik Tambak</label>
                                        <select name="user_id" class="form-control col-md-6">
                                            <option value=""> - Pilih Pemilik Tambak </option>
                                            @foreach($user as $option)
                                                <option value=" {{ $option->id }} " {{ ($option->id == $input['user_id']) ? 'selected' : '' }} > {{ $option->nama }} </option>
                                            @endforeach
                                        </select>
                                    </div>
                                @else
                                    <input type="hidden" name="user_id" value=" {{ $user->id }} ">
                                @endif
                               
                                <div class="form-group">
                                    <label for="">Nama Tambak</label>
                                    <input type="text" class="form-control col-md-6 input-value" id="NamaTambak" name="nama_tambak" required value=" {{ old('nama_tambak', $input['nama_tambak']) }} ">
                                </div>

                                <div class="form-group">
                                    <label for="">No Telepon</label>
                                    <input type="text" class="form-control col-md-6 input-value" id="No_Telp" name="no_telp" required value=" {{ old('no_telp', $input['no_telp']) }} ">
                                </div>
                                <div class="form-group">
                                    <label for="">Alamat</label>
                                    <input type="text" class="form-control col-md-6 input-value" id="Alamat" name="alamat" required value=" {{ old('alamat', $input['alamat']) }} ">
                                </div>

                                @if($input['foto'])
                                
                                <div class="form-group">
                                    <div class="col-md-6">
                                        <img src="{{ url('storage/foto/'. $input['foto']) }}" class="img-fluid">
                                    </div>
                                </div>

                                @endif
                                
                                <div class="form-group">
                                    <label for="">Foto</label>
                                    <input type="file" class="form-control col-md-4 input-value foto" id="Foto" accept="image/x-png,image/gif,image/jpeg" name="foto">
                                </div>

                                <div class="form-group">
                                    <input type="submit" value="Simpan" class="btn btn-primary float-right">
                                </div>
                                        
                            </form>
                             
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/admin/tambak/index.blade.php
@extends('admin.template')
@section('title')
Tambak
@endsection

@section('breadcumb')
Tambak
@endsection

@section('css')
<link rel="stylesheet" href="{{asset('admin/plugins/datatables.net-bs/css/dataTables.bootstrap.min.css')}}">
<link rel="stylesheet" href="{{asset('admin/plugins/fontawesome-free/css/all.min.css')}}">
  <!-- Ionicons -->

  <!-- DataTables -->
  <link rel="stylesheet" href="{{asset('admin/plugins/datatables-bs4/css/dataTables.bootstrap4.css')}}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{{asset('admin/dist/css/adminlte.min.css')}}">
@endsection

@section('content')

<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <div class="card-title">
                        Data Tambak
                    </div>
                    <div class="card-tools">
                        <a href=" {{ route('tambak.create') }} " class="btn btn-primary btn-tambah">Tambah Data <i class="fa fa-plus"></i></a>
                    </div>
                </div>
                <div class="card-body">
                    <br>
                    <div>
                      <table id="Table" class="table table-bordered table-hover">
                        <thead>
                          <tr>
                            <th>Nama Tambak</th>
                            <th>Alamat</th>
                            <th>No. Telp</th>
                            <th>Pemilik</th>
                            <th></th>
                          </tr>
                        </thead>
                        {{-- <tbody>
                            @foreach($tambak as $row)
                            <tr>
                                <td>{{ $loop->iteration }}</td>
                                <td>{{ $row->nama_tambak }}</td>
                                <td> {{ $row->alamat }} </td>
                                <td> {{ $row->no_telp }} </td>
                                <td> {{ $row->user->nama }} </td>
                                <td> 
                                    <form action=" {{ route('tambak.destroy', ['id' => $row->id]) }} " method="post">
                                    @csrf
                                    @method('delete')
                                        <a href=" {{ route('tambak.edit', ['id' => $row->id ]) }} " class="btn btn-warning btn-edit"><i class="fa fa-edit text-white"></i></a>
                                        
                                        <button type="submit" class="btn btn-danger btn-delete" onclick="return confirm('Yakin akan hapus data?')"><i class="fa fa-trash text-white"></i></button>
                                    </form>
                                </td>
                            </tr>
                            @endforeach
                        </tbody> --}}
                       
                      </table>
                    </div>
                </div>  
            </div>
        </div>
    </div>
</div>
@endsection

@section('js')
<script src="{{asset('admin/plugins/datatables.net/js/jquery.dataTables.min.js')}}"></script>
<script src="{{asset('admin/plugins/datatables.net-bs/js/dataTables.bootstrap.min.js')}}"></script>
<script src="{{asset('admin/plugins/datatables/jquery.dataTables.js')}}"></script>
<script src="{{asset('admin/plugins/datatables-bs4/js/dataTables.bootstrap4.js')}}"></script>
<script>

    $(document).ready(function(){
        $('.litambak').addClass('active');
      
       @if(session()->has('success'))
            toastr.success("{{session('success')}}")
            
       @endif
       
    })
   
    var Table =  $('#Table').DataTable({
                processing: true,
                serverSide: true,
                responsive: true,
                "paging": true,
                "lengthChange": true,
                "searching": true,
                "ordering": true,
                "info": true,
                "autoWidth": false,
                ajax: '{!! route('tambak.datatable') !!}',
                columns:[
                  {'data': 'nama_tambak'},
                  {'data': 'alamat'},
                  {'data': 'no_telp'},
                  {'data': 'nama_pemilik'},
                  {
                    data:"id",
                    
                    render: function(data, type, row){
                      
                        var button = `<a href="{{ route('tambak.edit', ['id' => ':id' ]) }}" class="btn btn-warning btn-edit"><i class="fa fa-edit text-white"></i></a>
                                      <a href="#" data-id=":idhapus" class="btn btn-danger btn-delete"><i class="fa fa-trash text-white"></i></a>
                        `
                                button = button.replace(':id',data);
                                button = button.replace(':idhapus',data);
                        return button;
                    }
                  }
                  
                ],
                "order": [[1,'asc']],
    
                rowId: 'id',
               
            });

            $(document).on('click', '.btn-delete', function(){
                var id = this.attributes['data-id'].value;
                var urlsnya = '{{ route("tambak.destroy", ":id") }}';
                    urlsnya = urlsnya.replace(':id', id);
                $.confirm({
                    theme: 'material',
                    title: 'Warning!',
                    content: 'Apakah anda yakin ingin menghapus data ?',
                    buttons: {
                        Yes: function () {
                            $.ajax({
                            type: 'POST',
                            dataType: 'json',
                            data: {
                                id: id,
                                "_token": "{{ csrf_token() }}",
                                _method: 'DELETE'
                            },
                            url: urlsnya,
                            })
                            .done(function(response) {
                                if(response == 1) {
                                    toastr.error('Data berhasil dihapus')
                                    Table.ajax.reload();
                                }
                            })
                            .fail(function() {
                                $.alert('Delete process fail');
                            })
                            .always(function() {
                                console.log("complete");
                            });
                        },
                        No: function () {
                        return;
                        }
                    }
                });
            });
   

  
</script>
@endsection