routes/web.php
<?php
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', 'HomeController@index')->name('home');
Route::get('/detail-ikan/{id}', 'HomeController@detail')->name('detail-ikan');
Route::get('/keluar', 'HomeController@logout')->name('keluar');

Route::get('/masuk','HomeController@login')->name('masuk');
Route::get('/daftar','HomeController@register')->name('daftar');
Route::post('/daftar-submit','HomeController@registersubmit')->name('register.submit');
Route::post('/login-submit','HomeController@loginsubmit')->name('login.submit');
Route::middleware('pelanggan-only')->group(function(){
    Route::get('/profil', 'HomeController@profil')->name('profil');
    Route::post('/profil-store', 'HomeController@profilstore')->name('profil.store');
    Route::get('/insert/cart/{id}', 'HomeController@insertcart')->name('insertcart');
    Route::get('/delete/cart/{id}', 'HomeController@deletecart')->name('deletecart');
    Route::get('/update/cart/{id}', 'HomeController@updatecart')->name('updatecart');
    Route::get('/cart', 'HomeController@cart')->name('cart');
    Route::get('/checkout', 'HomeController@checkout')->name('checkout');
    Route::post('/pembelian', 'HomeController@pembelian')->name('pembelian');
    Route::get('/list-pembelian', 'HomeController@listpembelian')->name('list.pembelian');
    Route::get('/pembelian/{id}/bayar', 'PembelianController@bayarpembelian')->name('pembayaran');
    Route::get('/pembelian/{id}/batal', 'PembelianController@batal')->name('pembayaran.batal');
    Route::post('/pembayaran/store', 'PembelianController@store')->name('pembayaran.store');
});

Route::prefix('admin')->group(function () {
    Auth::routes();
});

Route::middleware('auth')->group(function(){
    Route::get('/admin/dashboard','DashboardController@index')->name('dashboard');
    Route::middleware('admin-only')->group(function(){
        Route::resource('/admin/nelayan','NelayanController');
        Route::get('nelayandatatable','NelayanController@datatable')->name('nelayan.datatable');
        Route::resource('/admin/nelayan','NelayanController');
        Route::get('nelayandatatable','NelayanController@datatable')->name('nelayan.datatable');
        Route::resource('/admin/kabupaten','KabupatenController');
        Route::get('kabupatendatatable','KabupatenController@datatable')->name('kabupaten.datatable');
        Route::resource('admin/pelanggan', 'PelangganController');
        Route::resource('admin/admin', 'AdminController');
    });

    Route::resource('admin/ikan', 'IkanController');
    Route::get('ikandatatable','IkanController@datatable')->name('ikan.datatable');
    Route::resource('admin/tambak', 'TambakController');
    Route::get('tambakdatatable','TambakController@datatable')->name('tambak.datatable');

    Route::get('transaksi', 'TransaksiController@index');
    Route::get('transaksi/{transaksi_id}/detail', 'TransaksiController@detail')->name('transaksi.detail');
    Route::put('transaksi/{transaksi_id}/change-status', 'TransaksiController@changeStatus')->name('transaksi.change-status');
});

Route::get('ikan', 'ListingController@ikan');
Route::get('tambak', 'ListingController@tambak');
Route::get('tambak/{id}', 'ListingController@detailTambak');

resources/views/admin/dashboard.blade.php
@extends('admin.template')
@section('title')
Dashboard
@endsection

@section('breadcumb')
Dashboard
@endsection

@section('content')
<div class="container-fluid">
    <!-- Info boxes -->
    <div class="row">
      <div class="col-12 col-sm-6 col-md-3">
        <div class="info-box">
          <span class="info-box-icon bg-info elevation-1"><i class="fas fa-box"></i></span>

          <div class="info-box-content">
            <span class="info-box-text">Jumlah Produk</span>
            <span class="info-box-number">
              {{ $total_produk }}
            </span>
          </div>
          <!-- /.info-box-content -->
        </div>
        <!-- /.info-box -->
      </div>
      <!-- /.col -->
      <div class="col-12 col-sm-6 col-md-3">
        <div class="info-box mb-3">
          <span class="info-box-icon bg-danger elevation-1"><i class="fas fa-thumbs-up"></i></span>

          <div class="info-box-content">
            <span class="info-box-text">Jumlah Tambak</span>
            <span class="info-box-number">{{ $jumlah_tambak }}</span>
          </div>
          <!-- /.info-box-content -->
        </div>
        <!-- /.info-box -->
      </div>
      <!-- /.col -->

      <!-- fix for small devices only -->
      <div class="clearfix hidden-md-up"></div>

      <div class="col-12 col-sm-6 col-md-3">
        <div class="info-box mb-3">
          <span class="info-box-icon bg-success elevation-1"><i class="fas fa-shopping-cart"></i></span>

          <div class="info-box-content">
            <span class="info-box-text">Jumlah Transaksi</span>
            <span class="info-box-number">{{ $jumlah_transaksi }}</span>
          </div>
          <!-- /.info-box-content -->
        </div>
        <!-- /.info-box -->
      </div>
      <!-- /.col -->
      <div class="col-12 col-sm-6 col-md-3">
        <div class="info-box mb-3">
          <span class="info-box-icon bg-warning elevation-1"><i class="fas fa-dollar-sign"></i></span>

          <div class="info-box-content">
            <span class="info-box-text">Omset</span>
            <span class="info-box-number">{{ number_format($jumlah_omset) }}</span>
          </div>
          <!-- /.info-box-content -->
        </div>
        <!-- /.info-box -->
      </div>
      <!-- /.col -->
    </div>
    <!-- /.row -->

    <div class="row">
      <div class="col-md-12">
        <div class="card">
          <div class="card-header">
            Selamat Datang
          </div>
          <div class="card-body">
            Marketplace Ikan Mujair Desa Kedisan Kintamani
          </div>
        </div>
      </div>
    </div>

   
  </div><!--/. container-fluid -->
@endsection

@section('js')
<script>
   $(document).ready(function(){
        $('.lidashboard').addClass('active');
       
    })
</script>
@endsection

resources/views/admin/login.blade.php
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Admin | Log in</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- Font Awesome -->
  <link rel="stylesheet" href="{{asset('admin/plugins/fontawesome-free/css/all.min.css')}}">
  <!-- Ionicons -->
  {{-- <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css')}}"> --}}
  <!-- icheck bootstrap -->
  <link rel="stylesheet" href="{{asset('admin/plugins/icheck-bootstrap/icheck-bootstrap.min.css')}}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{{asset('admin/dist/css/adminlte.min.css')}}">
  <!-- Google Font: Source Sans Pro -->
  <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
</head>
<body class="hold-transition login-page">
<div class="login-box">
  <div class="login-logo">
    <a><b>Login</b></a>
  </div>
  <!-- /.login-logo -->
  <div class="card">
    <div class="card-body login-card-body">
      <p class="login-box-msg">Silahkan login terlebih dahulu</p>
      @if ($errors->any())
      <div class="alert alert-danger">
          <ul>
              @foreach ($errors->all() as $error)
                  <li>{{ $error }}</li>
              @endforeach
          </ul>
      </div>
    @endif
    <form action="{{route('login')}}" method="post">
        {{csrf_field()}}
        <div class="input-group mb-3">
          <input type="text" class="form-control" placeholder="Username" name="username">
          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-envelope"></span>
            </div>
          </div>
        </div>
        <div class="input-group mb-3">
          <input type="password" class="form-control" placeholder="Password" name="password">
          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-lock"></span>
            </div>
          </div>
        </div>
        <div class="row">
        
          <!-- /.col -->
          <div class="col-12">
            <button type="submit" class="btn btn-primary btn-block">Sign In</button>
          </div>
          <!-- /.col -->
        </div>
      </form>

      
      <!-- /.social-auth-links -->

     
    </div>
    <!-- /.login-card-body -->
  </div>
</div>
<!-- /.login-box -->

<!-- jQuery -->
<script src="{{asset('admin/plugins/jquery/jquery.min.js')}}"></script>
<!-- Bootstrap 4 -->
<script src="{{asset('admin/plugins/bootstrap/js/bootstrap.bundle.min.js')}}"></script>
<!-- AdminLTE App -->
<script src="{{asset('admin/dist/js/adminlte.min.js')}}"></script>

</body>
</html>

resources/views/admin/template.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <meta name="csrf-token" content="{{ csrf_token() }}">
  <title>@yield('title')</title>

  <!-- Font Awesome Icons -->
  <link rel="stylesheet" href="{{asset('admin/plugins/fontawesome-free/css/all.min.css')}}">
  <!-- overlayScrollbars -->
  <link rel="stylesheet" href="{{asset('admin/plugins/overlayScrollbars/css/OverlayScrollbars.min.css')}}">
  <link rel="stylesheet" href="{{asset('admin/plugins/jquery-confirm/css/jquery-confirm.css')}}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{{asset('admin/dist/css/adminlte.min.css')}}">
  <link rel="stylesheet" href="{{asset('admin/plugins/parsley-js/parsley.css')}}">
  <link rel="stylesheet" href="{{asset('admin/plugins/toastr/toastr.min.css')}}">
  <!-- Google Font: Source Sans Pro -->
  <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
  @yield('css')
</head>
<body class="hold-transition sidebar-mini layout-fixed layout-navbar-fixed layout-footer-fixed">
<div class="wrapper">
  <!-- Navbar -->
  <nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#"><i class="fas fa-bars"></i></a>
      </li>
     
    </ul>

    <!-- SEARCH FORM -->
   

    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
      <!-- Messages Dropdown Menu -->
      
      <li class="nav-item">
        <form action="{{ route('logout') }}" method="post">
          @csrf
          <button type="submit" class="nav-link">Logout</button>
        </form>
      </li>
    </ul>
  </nav>
  <!-- /.navbar -->

  <!-- Main Sidebar Container -->
  <aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="#" class="brand-link">
      <img src="{{asset('admin/dist/img/AdminLTELogo.png')}}" alt="AdminLTE Logo" class="brand-image img-circle elevation-3"
           style="opacity: .8">
      <span class="brand-text font-weight-light">
        @if(Auth::user()->level == 1)
          Admin
        @else 
          Nelayan 
        @endif
      </span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
      <!-- Sidebar user panel (optional) -->
      <div class="user-panel mt-3 pb-3 mb-3 d-flex">
        <div class="image">
          <img src="{{asset('admin/dist/img/user2-160x160.jpg')}}" class="img-circle elevation-2" alt="User Image">
        </div>
        <div class="info">
        <a href="#" class="d-block">{{Auth::user()->username}}</a>
        </div>
      </div>

      <!-- Sidebar Menu -->
      <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
          <!-- Add icons to the links using the .nav-icon class
               with font-awesome or any other icon font library -->
         
          <li class="nav-item">
            <a href="{{route('dashboard')}}" class="lidashboard nav-link">
              <i class="fas fa-circle nav-icon"></i>
              <p>Dashboard</p>
            </a>
          </li>
          @if(Auth::user()->level == 1)
          <li class="nav-item">
            <a href="{{route('admin.index')}}" class="liadmin nav-link">
              <i class="fas fa-circle nav-icon"></i>
              <p>Admin</p>
            </a>
          </li>
          <li class="nav-item">
            <a href="{{route('nelayan.index')}}" class="linelayan nav-link">
              <i class="fas fa-circle nav-icon"></i>
              <p>Nelayan</p>
            </a>
          </li>
          <li class="nav-item">
            <a href="{{route('pelanggan.index')}}" class="lipelanggan nav-link">
              <i class="fas fa-circle nav-icon"></i>
              <p>Pelanggan</p>
            </a>
          </li>
          <li class="nav-item">
            <a href="{{route('kabupaten.index')}}" class="likabupaten nav-link">
              <i class="fas fa-circle nav-icon"></i>
              <p>Kabupaten</p>
            </a>
          </li>
          @endif 
          <li class="nav-item">
            <a href="{{route('tambak.index')}}" class="litambak nav-link">
              <i class="fas fa-circle nav-icon"></i>
              <p>Tambak</p>
            </a>
          </li>
          <li class="nav-item">
            <a href="{{route('ikan.index')}}" class="liikan nav-link">
              <i class="fas fa-circle nav-icon"></i>
              <p>Ikan</p>
            </a>
          </li>

          <li class="nav-item">
            <a href="{{ url('transaksi') }}" class="litransaksi nav-link">
              <i class="fas fa-circle nav-icon"></i>
              <p>Transaksi</p>
            </a>
          </li>
          

          
        </ul>
      </nav>
      <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
  </aside>

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0 text-dark">@yield('title')</h1>
          </div><!-- /.col -->
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li class="breadcrumb-item active">@yield('breadcumb')</li>
            </ol>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-12">            
          @if ($errors->any())
          <div class="alert alert-danger">
              <ul>
                  @foreach ($errors->all() as $error)
                      <li>{{ $error }}</li>
                  @endforeach
              </ul>
          </div>
        @endif
        </div>
      </div>
    </div>
    <section class="content">
      
      @yield('content')
    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->

  <!-- Control Sidebar -->
  <aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
  </aside>
  <!-- /.control-sidebar -->

  <!-- Main Footer -->
  <footer class="main-footer">
    <strong>Copyright &copy; 2014-2019 <a href="http://adminlte.io">AdminLTE.io</a>.</strong>
    All rights reserved.
    <div class="float-right d-none d-sm-inline-block">
      <b>Version</b> 3.0.3-pre
    </div>
  </footer>
</div>
<!-- ./wrapper -->

<!-- REQUIRED SCRIPTS -->
<!-- jQuery -->
<script src="{{asset('admin/plugins/jquery/jquery.min.js')}}"></script>
<!-- Bootstrap -->
<script src="{{asset('admin/plugins/bootstrap/js/bootstrap.bundle.min.js')}}"></script>
<!-- overlayScrollbars -->
<script src="{{asset('admin/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js')}}"></script>
<!-- AdminLTE App -->
<script src="{{asset('admin/dist/js/adminlte.js')}}"></script>

<!-- OPTIONAL SCRIPTS -->
<script src="{{asset('admin/dist/js/demo.js')}}"></script>
<script src="{{asset('admin/plugins/jquery-confirm/js/jquery-confirm.js')}}"></script>

<!-- PAGE PLUGINS -->
<!-- jQuery Mapael -->
<script src="{{asset('admin/plugins/jquery-mousewheel/jquery.mousewheel.js')}}"></script>
<script src="{{asset('admin/plugins/raphael/raphael.min.js')}}"></script>
<script src="{{asset('admin/plugins/jquery-mapael/jquery.mapael.min.js')}}"></script>
<script src="{{asset('admin/plugins/jquery-mapael/maps/usa_states.min.js')}}"></script>
<!-- ChartJS -->
<script src="{{asset('admin/plugins/chart.js/Chart.min.js')}}"></script>
<script src="{{asset('admin/plugins/parsley-js/parsley.js')}}"></script>
<script src="{{asset('admin/plugins/toastr/toastr.min.js')}}"></script>


<!-- PAGE SCRIPTS -->
<script src="{{asset('admin/dist/js/pages/dashboard2.js')}}"></script>
@yield('js')
</body>
</html>