routes/web.php
<?php
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', 'HomeController@index')->name('home');
Route::get('/detail-ikan/{id}', 'HomeController@detail')->name('detail-ikan');
Route::get('/keluar', 'HomeController@logout')->name('keluar');

Route::get('/masuk','HomeController@login')->name('masuk');
Route::get('/daftar','HomeController@register')->name('daftar');
Route::post('/daftar-submit','HomeController@registersubmit')->name('register.submit');
Route::post('/login-submit','HomeController@loginsubmit')->name('login.submit');
Route::middleware('pelanggan-only')->group(function(){
    Route::get('/profil', 'HomeController@profil')->name('profil');
    Route::post('/profil-store', 'HomeController@profilstore')->name('profil.store');
    Route::get('/insert/cart/{id}', 'HomeController@insertcart')->name('insertcart');
    Route::get('/delete/cart/{id}', 'HomeController@deletecart')->name('deletecart');
    Route::get('/update/cart/{id}', 'HomeController@updatecart')->name('updatecart');
    Route::get('/cart', 'HomeController@cart')->name('cart');
    Route::get('/checkout', 'HomeController@checkout')->name('checkout');
    Route::post('/pembelian', 'HomeController@pembelian')->name('pembelian');
    Route::get('/list-pembelian', 'HomeController@listpembelian')->name('list.pembelian');
    Route::get('/pembelian/{id}/bayar', 'PembelianController@bayarpembelian')->name('pembayaran');
    Route::get('/pembelian/{id}/batal', 'PembelianController@batal')->name('pembayaran.batal');
    Route::post('/pembayaran/store', 'PembelianController@store')->name('pembayaran.store');
});

Route::prefix('admin')->group(function () {
    Auth::routes();
});

Route::middleware('auth')->group(function(){
    Route::get('/admin/dashboard','DashboardController@index')->name('dashboard');
    Route::middleware('admin-only')->group(function(){
        Route::resource('/admin/nelayan','NelayanController');
        Route::get('nelayandatatable','NelayanController@datatable')->name('nelayan.datatable');
        Route::resource('/admin/nelayan','NelayanController');
        Route::get('nelayandatatable','NelayanController@datatable')->name('nelayan.datatable');
        Route::resource('/admin/kabupaten','KabupatenController');
        Route::get('kabupatendatatable','KabupatenController@datatable')->name('kabupaten.datatable');
        Route::resource('admin/pelanggan', 'PelangganController');
        Route::resource('admin/admin', 'AdminController');
    });

    Route::resource('admin/ikan', 'IkanController');
    Route::get('ikandatatable','IkanController@datatable')->name('ikan.datatable');
    Route::resource('admin/tambak', 'TambakController');
    Route::get('tambakdatatable','TambakController@datatable')->name('tambak.datatable');

    Route::get('transaksi', 'TransaksiController@index');
    Route::get('transaksi/{transaksi_id}/detail', 'TransaksiController@detail')->name('transaksi.detail');
    Route::put('transaksi/{transaksi_id}/change-status', 'TransaksiController@changeStatus')->name('transaksi.change-status');
});

Route::get('ikan', 'ListingController@ikan');
Route::get('tambak', 'ListingController@tambak');
Route::get('tambak/{id}', 'ListingController@detailTambak');

app/Http/Controllers/NelayanController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use DB;
use Yajra\Datatables\Datatables;
use Auth;
use App\Tambak;
use App\User;
use Crypt;
class NelayanController extends Controller
{
    public function index(){
        return view('admin.nelayan.index');
    }
    public function datatable(){
        $data = DB::table('users')->join('tambak','users.id','tambak.user_id')->select('users.*','users.id as iduser','tambak.*', 
        \DB::raw('(CASE 
                        WHEN users.level = "0" THEN "Nelayan" 
                        WHEN users.level = "1" THEN "Admin" 
                        END) AS type')
        )->orderBy('users.created_at','DESC')->get();
      
        return Datatables::of($data)->make(true);
    }
    public function create()
    {
        $inputuser = User::defaultValues();
        $inputtambak = Tambak::defaultValues();
       
        return view('admin/nelayan/form', compact('inputuser', 'inputtambak'));
    }
    public function store(Request $request){
   
        $request->validate([
            'nama' => 'required',
            'email' => 'required|unique:users',
            'password' => 'required',
            'username' => 'required|unique:users',
            'nama_tambak' => 'required',
            'alamat' => 'required',
            'no_telp' => 'required|numeric',
            'foto' => 'required',        
        ]);
        //create
        if($request->iduser == null && $request->idtambak == null){
                
            $request->foto->store('foto');
                    
            
            $user = new User;
            $user->nama = $request->nama;
            $user->username = $request->username;
            $user->email = $request->email;
            $user->password = bcrypt($request->password);
            $user->level = 0;
            $user->save();
            $tambak = new Tambak;
            $tambak->nama_tambak = $request->nama_tambak;
            $tambak->no_telp = $request->no_telp;
            $tambak->alamat = $request->alamat;
            $tambak->foto = $request->foto->hashName();;
            $tambak->user_id = $user->id;
            
            $tambak->save();
            
            return redirect()->route('nelayan.index')->with('success', 'Berhasil menambah nelayan');
        }
        
     
    }

    public function edit($id){
       
        $inputuser = User::find($id);
       
        return view('admin/nelayan/form', compact('inputuser'));
    }
    public function update(Request $request,$id){
        $request->validate([
            'nama' => 'required',
            'email' => 'required',           
            'username' => 'required',            
        ]);
        // if(!Auth::validate(['username' => $request->username, 'password' => $request->password])){
        //     return redirect()->back()->with('error','Password tidak sesuai');
        // }
        $user = User::find($id);
        $user->nama = $request->nama;
        $user->username = $request->username;
        $user->email = $request->email;
        if($request->password != null){
            $user->password = bcrypt($request->password);
        }

        $user->update();
        return redirect()->route('nelayan.index')->with('success', 'Berhasil mengubah data nelayan');
    }
    public function destroy($id)
    {
        
        $user = User::find($id);
        $tambak = Tambak::where('user_id',$user->id)->delete();
       
        $user->delete();
        return 1;
    }

}

resources/views/admin/nelayan/form.blade.php
@extends('admin.template')
@section('title')
Nelayan
@endsection

@section('breadcumb')
Nelayan
@endsection

@section('content')

<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <div class="card-title">
                        Form Nelayan
                    </div>
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-12">
                            <form method="post" enctype="multipart/form-data" id="form" action="{{ (!isset($inputuser['id'])) ? route('nelayan.store') : route('nelayan.update', ['id' => $inputuser['id']]) }}">
                                {{csrf_field()}}

                                @isset($inputuser['id'])
                                    {{ method_field('PUT')}}
                                @endisset
                                <b>Data User</b>
                                <hr>
                                
                                <div class="form-group">
                                    <label for="">Nama</label>
                                    <input type="text" class="form-control col-md-6 input-value" id="Nama" name="nama" required value=" {{ old('nama', $inputuser['nama']) }} ">
                                </div>
                               
                                <div class="form-group">
                                    <label for="">Email</label>
                                    <input type="text" class="form-control col-md-6 input-value" id="Email" name="email" required value=" {{ old('email', $inputuser['email']) }} ">
                                </div>
                                <div class="form-group">
                                    <label for="">Username</label>
                                    <input type="text" class="form-control col-md-6 input-value" id="Username" name="username" required value=" {{ old('username', $inputuser['username']) }} ">
                                </div>
                                <div class="form-group form-password">
                                    <label for="">Password</label>
                                    <input type="password" class="form-control col-md-6 input-value" id="Password" name="password">
                                </div>
                                

                                @if(!$inputuser['username'])
                                <br>
                                <br>
                                <b>Data Tambak</b>
                                <hr>
                                <input type="hidden" class="form-control col-md-6 input-value" id="idtambak" name="idtambak" required>
                                <div class="form-group">
                                    <label for="">Nama Tambak</label>
                                    <input type="text" class="form-control col-md-6 input-value" id="NamaTambak" name="nama_tambak" required>
                                </div>
                                <div id="imagePreview">
                                   
                                </div>
                                <div class="form-group">
                                    <label for="">Foto</label>
                                    <input type="file" class="form-control col-md-6 input-value foto" id="Foto" accept="image/x-png,image/gif,image/jpeg" name="foto" required>
                                </div>
                                <div class="form-group">
                                    <label for="">No Telepon</label>
                                    <input type="text" class="form-control col-md-6 input-value" id="No_Telp" name="no_telp" required>
                                </div>
                                <div class="form-group">
                                    <label for="">Alamat</label>
                                    <input type="text" class="form-control col-md-6 input-value" id="Alamat" name="alamat" required>
                                </div>
                                        
                                @endif
                                

                                <div class="form-group">
                                    <input type="submit" value="Simpan" class="btn btn-primary float-right">
                                </div>
                                        
                            </form>
                             
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

@section('js')
<script>
    $(document).ready(function(){
        $('.linelayan').addClass('active');
        @if(session('error'))
            toastr.error("{!! session('error') !!}")
       @endif
        $('.change').click(function(){
            $(this).hide();
            $('.form-newpassword').removeAttr('hidden');
            $('.cancel-change').show()
        })
        $('.cancel-change').click(function(){
            $(this).hide();
            $('.change').show();
            $('.form-newpassword').attr('hidden','hidden');
        })
    })
   
</script>
    
@endsection

resources/views/admin/nelayan/index.blade.php
@extends('admin.template')
@section('title')
Nelayan
@endsection

@section('breadcumb')
Nelayan
@endsection

@section('css')
<link rel="stylesheet" href="{{asset('admin/plugins/datatables.net-bs/css/dataTables.bootstrap.min.css')}}">
<link rel="stylesheet" href="{{asset('admin/plugins/fontawesome-free/css/all.min.css')}}">
  <!-- Ionicons -->

  <!-- DataTables -->
  <link rel="stylesheet" href="{{asset('admin/plugins/datatables-bs4/css/dataTables.bootstrap4.css')}}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{{asset('admin/dist/css/adminlte.min.css')}}">
@endsection

@section('content')

{{-- <div class="modal fade" id="modal-lg">
    <div class="modal-dialog modal-lg">
      <div class="modal-content">
        <div class="modal-header">
          <h4 class="modal-title">Form</h4>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          @include('admin.nelayan.form')
        </div>
        <div class="modal-footer justify-content-between">
          <button type="button" class="btn btn-default" data-dismiss="modal">Tutup</button>
          <button type="button" class="btn btn-primary btn-submit">Simpan</button>
        </div>
      </div>
      <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
  </div> --}}
<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <div class="card-title">
                        Data Nelayan
                    </div>
                    <div class="card-tools">
                        <a  href="{{route('nelayan.create')}}" class="btn btn-primary btn-tambah">Tambah Data <i class="fa fa-plus"></i></a>
                    </div>
                </div>
                <div class="card-body">
                    <br>
                    <div>
                      <table id="Table" class="table table-bordered table-hover">
                        <thead>
                          <tr>
                            <!-- <th>Foto</th> -->
                            
                            <th>Nama</th>
                            <th>Email</th>
                            <th>No Telepon</th>
                            <th>Alamat</th>
                            <th>Type</th>
                            <th></th>
                          </tr>
                        </thead>
                        <tbody>
      
                        </tbody>
                       
                      </table>
                    </div>
                </div>  
            </div>
        </div>
    </div>
</div>
@endsection

@section('js')
<script src="{{asset('admin/plugins/datatables.net/js/jquery.dataTables.min.js')}}"></script>
<script src="{{asset('admin/plugins/datatables.net-bs/js/dataTables.bootstrap.min.js')}}"></script>
<script src="{{asset('admin/plugins/datatables/jquery.dataTables.js')}}"></script>
<script src="{{asset('admin/plugins/datatables-bs4/js/dataTables.bootstrap4.js')}}"></script>
<script>

    $(document).ready(function(){
        $('.linelayan').addClass('active');
      
       @if(session()->has('success'))
            toastr.success("{{session('success')}}")
            
       @endif
       
    })
    // var Filefoto;
    // $('#Foto').change(function(){
    //     var fileInput = this;
    //         console.log(fileInput.files[0])
    //         Filefoto = fileInput.files[0];
    //     var filePath = fileInput.value;
        
        
    //         //Image preview
    //         if (fileInput.files && fileInput.files[0]) {
    //             var reader = new FileReader();
    //             reader.onload = function(e) {
    //                 document.getElementById('imagePreview').innerHTML = '<img src="'+e.target.result+'" width="250px" heighth="250px"/>';
    //             };
    //             reader.readAsDataURL(fileInput.files[0]);
    //         }
    // })
    var Table =  $('#Table').DataTable({
                processing: true,
                serverSide: true,
                responsive: true,
                "paging": true,
                "lengthChange": true,
                "searching": true,
                "ordering": true,
                "info": true,
                "autoWidth": false,
                ajax: '{!! route('nelayan.datatable') !!}',
                columns:[
                  {'data': 'nama'},
                  {'data': 'email'},
                  {'data': 'no_telp'},
                  {'data': 'alamat'},
                  {'data': 'type'},
                  {
                    data:"iduser",
                    
                    render: function(data, type, row){
                      
                        var button = `<a href="{{ route('nelayan.edit', ['id' => ':id' ]) }}" class="btn btn-warning btn-edit"><i class="fa fa-edit text-white"></i></a>
                                      <a href="#" class="btn btn-danger btn-delete" data-id=":idhapus"><i class="fa fa-trash text-white"></i></a>
                        `
                                button = button.replace(':id',data);
                                button = button.replace(':idhapus',data);
                        return button;
                    }
                  }
                  
                ],
                "order": [[1,'asc']],
    
                rowId: 'id',
               
            });

    // $('.btn-tambah').on('click', function(){
    //     $('.input-value').val("");
    // })
    // $('.btn-submit').on('click', function(){
    //         var checkrequired = $('input,textarea,select').filter('[required]:visible')
    //         var isValid = true;
            
    //         $(checkrequired).each( function() {
    //                 if ($(this).parsley().validate() !== true) isValid = false;
    //         });
    //         if(!isValid){
    //             return;
    //         }
            
    //         urlsnya = '{{route('nelayan.store')}}';
    //         _token = $('.form_content').find('input[name=_token]').val();
    //         form = $('.form_content').find('.input-value');
    //         var arr= {};
           
    //         var file = new FormData();
    //          file.append('file', Filefoto);
    //          $.each(form,function(k,value){
    //             file.append(value.name,value.value);
               
    //         });
    //         $.ajax({
    //             headers: {
    //                 'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
    //             },
    //             type: 'POST',
    //             contentType: false,
    //             processData: false,
    //             dataType: 'json',
    //             data: file,
    //             url: urlsnya,
    //         })
    //         .done(function(response) {
    //             if(response == 1){
    //                 toastr.success('Data berhasil disimpan')
    //                 Table.ajax.reload();
    //                 $('#modal-lg').modal('hide');
    //                 $('.input-value').val("");
    //                 $(checkrequired).each( function() {
    //                     $(this).parsley().reset();
    //                 });
    //             }
    //         })
    //         .fail(function() {
    //             $.alert('process fail');
    //         })
    //         .always(function() {
    //             console.log("complete");
    //         });
    //     });

    //     $(document).on('click', '.btn-edit', function(){
            
    //         var id = this.attributes['data-id'].value;

    //         $('.form-password').remove();
    //         $('#Foto').removeAttr('required');


    //         var urlsnya = '{{ route("nelayan.edit", ['id'=>":id"]) }}';
    //         urlsnya = urlsnya.replace(':id', id);
    //         $.ajax({
    //             type: 'GET',
    //             dataType: 'json',
    //             data: {
    //                 id: id,
    //                 "_token": "{{ csrf_token() }}"
    //             },
    //             url: urlsnya,
    //         })
    //         .done(function(response){
    //             console.log(response[0])
    //             $('#modal-lg').modal()
    //             $('#iduser').val(response[0]['iduser'])
    //             $('#Nama').val(response[0]['nama'])
    //             $('#Username').val(response[0]['username'])
    //             $('#Email').val(response[0]['email'])
    //             $('#NamaTambak').val(response[0]['nama_tambak'])
    //             $('#No_Telp').val(response[0]['no_telp'])
    //             $('#Alamat').val(response[0]['alamat'])
    //             $('#imagePreview').append(`<img src="{{asset('img/')}}/`+response[0]['foto']+`" width="250px" heighth="250px"/>`)
    //         })
    //     })

        $(document).on('click', '.btn-delete', function(){
            var id = this.attributes['data-id'].value;
            var urlsnya = '{{ route("nelayan.destroy", ":id") }}';
                urlsnya = urlsnya.replace(':id', id);
            $.confirm({
                theme: 'material',
                title: 'Warning!',
                content: 'Apakah anda yakin ingin menghapus data ?',
                buttons: {
                    Yes: function () {
                        $.ajax({
                        type: 'POST',
                        dataType: 'json',
                        data: {
                            id: id,
                            "_token": "{{ csrf_token() }}",
                            _method: 'DELETE'
                        },
                        url: urlsnya,
                        })
                        .done(function(response) {
                            if(response == 1) {
                                toastr.error('Data berhasil dihapus')
                                Table.ajax.reload();
                            }
                        })
                        .fail(function() {
                            $.alert('Delete process fail');
                        })
                        .always(function() {
                            console.log("complete");
                        });
                    },
                    No: function () {
                    return;
                    }
                }
            });
        });

  
</script>
@endsection